config/routes.rb
Rails.application.routes.draw do

  controller :root do 
    get :about
    get :rules
    get :privacy
    get :contact
  end


  controller :tasks do
    root 'tasks#index' 
    resources :tasks do
      post :confirm, action: :confirm_new, on: :new 
      post :import, on: :collection
    end
  end


  namespace :admin do
    resources :users
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :contacts, only: %i(new create)

end

app/models/task.rb
class Task < ApplicationRecord

  # acts_as_taggable_on :tags と同じ意味のエイリアス
  # tags の中にIDやら名前などが入る,イメージ的には親情報
  acts_as_taggable


  # メソッド名の前にselfをつけることでクラスメソッドを定義することができる
  # CSVデータにどの属性をどの順番で出力するかをcsv_attributesと言うクラスメソッドから得られるように定義している
  def self.csv_attributes
    ["name","description","created_at","updated_at"]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|  # CSV.generateを使ってCSVデータの文字列を生成します。生成した文字列がgenerate_csvクラスメソッドの戻り値となる
      csv << csv_attributes # CSVの1行目としてヘッダを出力します。
      all.each do |task|
        csv << csv_attributes.map{|attr| task.send(attr) }
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      task = new
      task.attributes = row.to_hash.slice(*csv_attributes)
      task.save!
    end
  end


  # レコードとファイルの間に 1対1のマッピングを設定します。各レコードには1つのファイルを添付します。 
  has_one_attached :image

  # %wは配列を作る、配列の要素のスペース区切りで指定する ( 式の展開はされない )
  # ransaclable_attributesには検索対象にすることを許可するカラムを指定する、デフォルトでは全てのカラムを対象としている。
  # 指定されなかったカラムがransackに渡されても無視されるようになります。
  def self.ransackable_attributes(auth_object = nil)
    %w[name created_at]
  end

  
  # ransackable_associationsは検索条件に含める関連を指定できる
  # このメソッドをからの配列を返すようにオーバーライドすることで、検索条件に意図しない関連を含め内容にすることができます
  def self.ransackable_associations(auth_object = nil)
    []
  end





  # 検証前の正規化
  before_validation :set_nameless_name
  validates :name, presence: true, length: { maximum: 30 }


  # オリジナルな検証コードをかく
  validate :validate_name_not_including_comma


  # そのクラス(ここではTask)がある別のクラス(ここではUser)に従属しており、従属先のクラスのidを外部キーとして抱えていることを表しています。
  # いわば親分を指定するようなイメージ
  # このような定義をすることでUserクラスのインスタンスに対して、user.tasksといったメソッドで紐づいたTaskオブジェクトの一覧を得られるようになります
  # またTaskクラスのインスタンスに対しては、task.userで紐づいたUserオブジェクトを得られるようになります
  belongs_to :user

  scope :recent, -> { order(created_at: :desc )}


    private 
     
      # &. ぼっち演算子を使って、nameがnilの場合には例外が発生するのを避けるために &.を利用して,nameがnilの時にはこの検証(errors.addをしない)ようにしている
      def validate_name_not_including_comma
        errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
      end

      # コールバックの実装 三項演算子
      def set_nameless_name
        self.name = '名前なし' if name.blank?
      end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    # 検索パラメーターのデフォルトのパラメーターキーは :searchではなく、:qになった
    # 検索フォームの入力内容で検索する
    @q = current_user.tasks.ransack(params[:q])
    # 重複を排除
    @tasks = @q.result(distinct: true).page(params[:page])

    if params[:tag_name]
      @tasks = @tasks.tagged_with("#{params[:tag_name]}") # tagged_with("タグ名")で絞り込む
    end


    # 先ほどselfメソッドで定義したクラスメソッドを呼び出すコントローラーを実装する
    # 新しいアクションを作るのではなく「一覧表示のindexアクションに異なるフォーマットでの出力機能を用紙する」と捉える
    respond_to do |format| # format.htmlはHTMLとしてアクセスされた場合(URLに拡張子なしでアクセスされた場合), format.csvはCSVとしてアクセスされた場合(/task.csvというURLでアクセスされた場合)に実行される
      format.html # HTMLフォーマットについてはslimのindex画面が表示されるだけ
      format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv"} # send_dataメソッドを使ってレスポンスを送り出し、送り出したデータをブラウザからファイルとしてDLできるようにする
    end
  end

  def show
    # params[:id]にはリクエストパラメーター(params)から得られるid,つまりリクエストされたURL "tasks/[タスクのid]の
    # [タスクのid]部分が格納されてます"
  end

  # エラーハンドリングの実装をする
  def create
    @task = current_user.tasks.new(task_params)

    if params[:back].present?
      render :new
      return
    end

    if @task.save
      TaskMailer.creation_email(@task).deliver_now
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else 
      render :new
    end
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def update 
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
    # 今回はサーバーサイドでタスクを削除すればいい。
    # HTTPメソッドだとDELETEなので、リクエストは200か204を返す必要がある
    # またDLETEの場合は、処理だけ受け付けて実際の消去をしない場合は202を返すみたいに
    head :no_content
  end

  # 確認画面を表示するアクションを追加する
  # 新規登録画面から送られてきた情報の検証を行い、問題があれば新規登録画面を検証メッセージと共に表示する
  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def import 
    current_user.tasks.import(params[:file])
    redirect_to tasks_url, notice: "タスクを追加しました"
  end


  private 


    # フォームからリクエストパラメーターとして送られてきた情報が想定どおりであることをチェックし
    # 受け付ける想定であるname(名称)とdescription(詳しい説明)の情報だけを抜き取る役割をしてる
    def task_params 
      params.require(:task).permit(:name, :description, :image, :tag_list)
    end

    def set_task
      @task = current_user.tasks.find(params[:id])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.slim
// エラーメッセージの検証
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message 
      
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
    // タグ入力フォーム
    .form-group
    = f.label :tag_list
    = f.text_field :tag_list, value: @task.tag_list.join(','), class: "form-control"

    
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/_tag_list.html.slim
- tag_list.each do |tag|
  span.badge.badge-primary.mr-1.p-2
    = link_to tag, tasks_path(tag_name: tag), class: "text-white"
// 受け取ったパラメーターを繰り返し処理し、一つ一つを分けて表示させる
// 

app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:name)
        th= @task.name
        = f.hidden_field :name

      tr
        th= Task.human_attribute_name(:description)
        th= simple_format(@task.description)
        = f.hidden_field :description
   
    // モデル「ボタンに 'back' という名前を与えているので戻るボタンは押された時はparams[:back]で "戻る" という文字列を得られます

    = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
    = f.submit '登録', class: 'btn btn-primary'
      

app/views/tasks/destory.js.erb
// このJavaScriptビューとして出力されるように、先ほどTasksController#destoryに加えた head :no_contentを削除する


document.querySelector("#task-<%= @task.id %>").style.display = 'none';

var message = document.createElement('p');
message.innerText = 'タスク「<%= @task.name %>」を削除しました。残りのタスクは<%= Task.name %>件です。 ';
document.querySelector('table')insertAdjacentElement('beforebegin', message);

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }
// ここ調べる render partial: 'レンダリングするところ', locals ( このlocalsはどういう意味で使ってるの？ )

app/views/tasks/index.html.slim
.top
  .top.margin






= search_form_for @q, class: 'mb-5' do |f|


  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-gruop.row
    = f.label :created_at_gtaq, '登録日時', class: 'col-sm2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
    

    .form-group
      = f.submit class: 'btn btn-primary'


= link_to '新規登録', new_task_path, class: 'btn btn-primary'
= link_to 'エクスポート', tasks_path(format: :csv),class: 'btn btn-primary mb-6 ml-4'

.mt-4
  = paginate @tasks
  = page_entries_info @tasks

= form_tag import_tasks_path, multipart: true, class: 'mb-3 mt-5' do
  = file_field_tag :file
  = submit_tag "インポート", class: 'btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      // ransackの提供するsort_linkヘルパーを利用する、こうすることでソート操作ができる見出し部分を表示することができる ( 第一引数にはransackメソッドで呼び出して得られたRansack::Searchオブジェクト(ここでは@q)
      // 第二引数にはソートを行う対象のカラム(ここでは「名称」を表す:name)を指定します)
      th = sort_link(@q, :name)
      th = Task.human_attribute_name(:created_at)
      th = Task.human_attribute_name(:tag_list)
      th

    tbody 
      - @tasks.each do |task|
        tr id="task-#{task.id}"
          // クリックすると "tasks/[タスクID]"という詳細表示のURLに還移するようになる
          td= link_to task.name, task_path(task)
          td= task.created_at
          // タグ表示欄を追加する
          td= render 'tasks/tag_list', tag_list: task.tag_list


          td 
            = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-4'
            = link_to '削除', task, method: :delete, remote: true, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか〜？"}, class: 'btn btn-danger delete',id: "delete_link_#{task.id}"
            // 上記のlink_to メソッドが出力したHTML(a要素)をみてみると、data-remote属性が付与されていることがわかる。
            // remote: trueを設定すると何が変わるかを一言でいうと、リクエストのhtml形式ではなくjs形式になる

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }


  // form_withブロックの最後ではsubmitヘルパーを呼んでいます
  // これによって以下のようなsubmitボタンを表す
  // <input type="submit" name="commit" value="登録する" class="btn btn-primary" data-disable-with="登録する">
  // ここの登録するはlocalesファイルにデフォルトで設定されている用語が適用されているため
  
  // localsオプションはパーシャル内のローカル変数を設定してます。locales: { task: @task }と記述すると「インスタンス変数@taskをパーシャルないのローカル変数taskとして
  // 渡す」という意味なる。これにより、ローカル変数をパーシャルから利用できるようになる

// 新規登録画面からの還移先を変える
- if @task.errors.present?
  ul#error_explanation
    - @task.errors.full_messages.each do |message|
      li = message
  
//
  = form_with model: @task, local: true, url: confirm_new_task_path do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', id: 'task_name'
    .form-group
      = f.label :description
      = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
    = f.submit '確認', class: 'btn btn-primary'

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr 
      th= Task.human_attribute_name(:name)
      td= @task.name 
    tr 
      th= Task.human_attribute_name(:description)
      td= auto_link(simple_format(h(@task.description),{}, santiize: false, wrapper_tag: "div")) 
    tr
      th= Task.human_attribute_name(:image)
      td= image_tag @task.image if @task.image.attached?
    
    tr
      th= Task.human_attribute_name(:created_at)
      th= @task.created_at
    tr 
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか〜？"}, class: 'btn btn-danger'