config/routes.rb
Rails.application.routes.draw do

  controller :root do 
    get :about
    get :rules
    get :privacy
    get :contact
  end


  controller :tasks do
    root 'tasks#index' 
    resources :tasks do
      post :confirm, action: :confirm_new, on: :new 
      post :import, on: :collection
    end
  end


  namespace :admin do
    resources :users
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :contacts, only: %i(new create)

end

app/views/layouts/_default.slim
meta[name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"]
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_footer.html.slim
footer.footer
  .footer__nav
    = link_to 'Todorailsとは', about_path, class: 'footer__nav__item'
    = link_to 'お問い合わせ', contact_path, class: 'footer__nav__item'
    = link_to '利用規約', rules_path, class: 'footer__nav__item'
    = link_to 'プライバシーポリシー', privacy_path, class: 'footer__nav__item'
  .footer__copy &copy;2019 TodoRails All Rights Reserved.

app/views/layouts/_navbar.html.slim
navbar.navbar.navbar--pc
  .navbar__heading
    .navbar__heading__contents todoリスト
  .navbar__contens
    = link_to 'Todorails', root_path, class: 'navbar__logo'
    .navbar__nav
      = link_to root_path, class: 'navbar__nav__item' do
        i.fa.fa-serach
    - if current_user
      = link_to 'タスク一覧', tasks_path, class: 'navbar__nav__item btn--header'
    - else
      = link_to 'はじめる', login_path,class: 'navbar__nav__item btn--header'














//navbar.navbar
    ul.nav.justify-content-end
      - if current_user
        li.nav-item= link_to 'タスク一覧', tasks_path, class: 'btn btn-primary'
        li.nav-item= link_to '' , '#' , class: 'nav-link.commonNavIcon.profile-icon'
        // ログインしているユーザーがk管理権限を持っている場合のみ、ナビゲーションにユーザー一覧画面へのリンクが表示されるようになった
        - if current_user.admin?
          li.nav-item= link_to 'ユーザー一覧', admin_user_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
          li.nav-item= link_to 'サインアップ'
        - else
          li.nav-link= link_to 'ログイン', login_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_ttl(yield(:ttl))

    link[rel='shortcut icon' href='/images/icon.png']
    link[rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.1/css/all.css' integrity='sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr' crossorigin='anonymous']
    link[href='https://fonts.googleapis.com/css?family=Noto+Sans+JP' rel='stylesheet']

    = render 'layouts/default'

  body
    = render 'layouts/navbar'
    = render 'layouts/footer'
  
  .container  
        
    = yield

app/views/layouts/users.html.slim
doctype html 
html 
  head 
    title 
      | TodoRails 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-tubolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-tubolinks-track': 'reload'

    body 

    .container 
      // view/users/show.html.viewから引っ張ってきてる
      = yield